server:
  port: 8002

spring:
  application:
    name: order-tracker-notification

  datasource:
    url: jdbc:postgresql://localhost:5432/order_track_notification
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl:auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
